export default {
  name: 'TJ Mazeika',
  position: 'Mid-level software engineer at JPMorgan Chase & Co. with three years of professional and 12 years of personal experience.',
  location: 'Austin, TX',
  email: 'mazeika.tj@gmail.com',
  githubUsername: 'tmazeika',
  skills: [
    {
      category: 'Languages',
      items: ['Kotlin', 'Java', 'TypeScript', 'Go'],
    },
    {
      category: 'Tools',
      items: ['Ktor', 'Spring Boot', 'Node.js/Next.js', 'PostgreSQL', 'MongoDB', 'Docker', '*nix', 'AWS'],
    },
    {
      category: 'Interests',
      items: [
        'Full-stack web development',
        // 'operating systems',
        // 'compilers',
        // 'programming languages',
        'functional programming',
        // 'optimization',
      ],
    },
  ],
  education: [
    {
      company: 'Northeastern University',
      position: 'Bachelor of Science in Computer Science, summa cum laude',
      location: 'Boston, MA',
      start: 'September 2018',
      end: 'December 2021',
    },
  ],
  experience: [
    {
      company: 'JPMorgan Chase & Co.',
      position: 'Software Engineer III',
      location: 'Austin, TX',
      start: 'December 2022',
      end: 'Present',
      body: [
        "Engineered critical back-end features for a public web-based developer console used for managing access to JPMorgan Payments APIs. Written in Java with Spring Boot, WebFlux, Liquibase, Hibernate, and Amazon Aurora. Successfully dealt with the challenges of a large, legacy codebase, addressing performance and consistency concerns in a distributed microservices arcitecture.",
        "Authored thorough design documents and executed Agile spike stories in response to evolving requirements and a complex, highly uncertain environment. Actively presented solutions and offered insights during daily standups, sprint planning sessions, and retrospectives.",
      ],
    },
    {
      company: 'Urban Emu',
      position: 'Software Engineer',
      location: 'Remote',
      start: 'August 2021',
      end: 'December 2022',
      body: [
        "Produced the agency's first interactive Next.js SPA from scratch. This fetched data from the USDA's database of foods (FDC) to enable a select group of client-employed nutritionists to build healthy eating plans with live nutrition fact aggregations. Its completion elevated the agency's advertised capabilities.",
        'Supported the back-end and front-end development of several US government-owned web properties including Next.js, Drupal, and Wordpress deployments. Worked in an international team of four to build features including filtered and paginated fuzzy searching of a database, as well as a trending content page based on the z-score of page view changes over time (PHP).',
      ],
    },
    {
      company: 'FoldLeft',
      position: 'Founder & Software Engineer',
      location: 'Remote',
      start: 'November 2020',
      end: 'December 2022',
      body: [
        'Founded an LLC to offer web development services to several small businesses and startups. Started greenfield projects and enhanced existing ones. Managed all invoicing, bookkeeping, and client outreach.',
        'Bootstrapped a fintech startup from Figma designs (Next.js, Prisma, tRPC). Integrated third-party financial services to pull users\' debts, credit reports, and automated valuation models (AVMs) of properties.',
      ],
    },
    {
      company: 'AIR Worldwide',
      position: 'Software Engineer Co-op',
      location: 'Boston, MA',
      start: 'January',
      end: 'June 2021',
      body: [
        'Enriched product owner insights into team productivity by tracking Azure DevOps issue-closing activity from its REST and OData API endpoints; displayed in graphs with the Highcharts library.',
        'Halved the data loading time of an internal application (C#, .NET, React) by parallelizing back-end and front-end network calls. In weekly live surveys thereafter, users reported a significantly improved UX.',
      ],
    },
    // {
    //   company: 'Digitas',
    //   position: 'DevOps Engineer Co-op',
    //   location: 'Boston, MA',
    //   start: 'January',
    //   end: 'July 2020',
    //   body: [
    //     "Eliminated flakiness in a QA automation suite (Selenium, Java), which decreased runtime from 6 hours to just 30 minutes, by waiting for elements to become interactive before running assertions on them. This enabled QA to run tests on-demand, rather than once daily, and built confidence in quality team-wide.",
    //     'Wrote clear and concise documentation for deploying an SAP Hybris and Adobe AEM application to staging and production clusters (Git, Bash), guaranteeing the success and consistency of manual deployments.',
    //   ],
    // },
  ],
  keywords: [
    'Agile',
    'Android',
    'backend',
    'Bash',
    'C',
    'C++',
    'C/C++',
    'CI/CD',
    'CSS',
    'Cypress',
    'Dart',
    'database design',
    'Flutter',
    'formal verification',
    'GCP',
    'Git',
    'GitHub',
    'Gradle',
    'HTML',
    'iOS',
    'iPhone',
    'JavaScript',
    'JetBrains',
    'Jira',
    'JS',
    'Linux',
    'macOS',
    'Make',
    'Maven',
    'NoSQL',
    'object oriented programming',
    'PHP',
    'Prisma',
    'Python',
    'Racket',
    'relational databases',
    'scripting',
    'Shell',
    'SQL',
    'Swift',
    'Tailwind CSS',
    'Vim',
    'VSCode',
    'Yarn',
  ],
} as const;
