export default {
  name: 'TJ Mazeika',
  position: 'Software Engineer',
  location: 'Austin, TX',
  email: 'mazeika.tj@gmail.com',
  githubUsername: 'tmazeika',
  skills: [
    {
      category: 'Languages',
      items: ['TypeScript', 'Go', 'Java'],
    },
    {
      category: 'Tools',
      items: ['Node.js/Next.js', 'Vercel', 'Firebase', 'MongoDB', 'PostgreSQL', 'Docker', '*nix'],
    },
    {
      category: 'Interests',
      // items: [
      //   'Full-stack web development',
      //   'operating systems',
      //   'compilers',
      //   'programming languages',
      //   'functional programming',
      //   'optimization',
      // ],
      items: [
        'Full-stack web development',
        'functional programming',
      ],
    },
  ],
  education: [
    {
      company: 'Northeastern University',
      position: 'Bachelor of Science in Computer Science, summa cum laude',
      location: 'Boston, MA',
      start: 'September 2018',
      end: 'December 2021',
    },
  ],
  experience: [
    {
      company: 'Urban Emu',
      position: 'Software Engineer',
      location: 'Remote',
      start: 'January 2022',
      end: 'Present',
      body: [
        "Produced the agency's first interactive Next.js SPA from scratch. This fetched data from the USDA's FoodData Central database to enable nutritionists to build healthy eating plans with live nutrition fact aggregations. Its completion expanded the breadth of development services available to clients.",
        'Supported the back-end and front-end development of several US government-owned web properties including Next.js, Drupal, and Wordpress deployments. Worked in a small yet international team to build features including filtered and paginated fuzzy searching of a database, as well as a trending content page based on the z-score of page view changes over time.',
      ],
    },
    {
      company: 'FoldLeft',
      position: 'Founder & Software Engineer',
      location: 'Remote',
      start: 'November 2020',
      end: 'Present',
      body: [
        'Founded an LLC to offer web development services to several small businesses and startups. Started greenfield projects and enhanced existing ones. Managed all invoicing, bookkeeping, and client outreach.',
        'Bootstrapped a fintech startup from Figma designs (Next.js, Prisma, Tailwind CSS). Continuously accomodated changing client requirements and promptly responded to feedback throughout.',
      ],
    },
    {
      company: 'AIR Worldwide',
      position: 'Software Engineer Co-op',
      location: 'Boston, MA',
      start: 'January',
      end: 'June 2021',
      body: [
        'Enriched product owner insights into team productivity by tracking Azure DevOps issue-closing activity from its REST and OData API endpoints; displayed in graphs with the Highcharts library.',
        'Halved the 10-second time-to-hydration of an internal application (C#, .NET, React) by parallelizing back-end and front-end network calls. In weekly surveys thereafter, users reported an improved UX.',
        'Pair-programmed with team members and submitted code reviews to promote code quality.',
      ],
    },
    {
      company: 'Digitas',
      position: 'DevOps Engineer Co-op',
      location: 'Boston, MA',
      start: 'January',
      end: 'July 2020',
      body: [
        "Eliminated flakiness in a QA automation suite (Selenium, Java), which decreased runtime from 6 hours to just 30 minutes, by waiting for elements to become interactive before running assertions on them. This enabled QA to run tests on-demand, rather than once daily, and built confidence in quality team-wide.",
        'Wrote clear and concise documentation for deploying an SAP Hybris and Adobe AEM application to staging and production clusters, guaranteeing the success and consistency of manual deployments.',
      ],
    },
  ],
  keywords: [
    'Agile',
    'Android',
    'backend',
    'Bash',
    'C',
    'C++',
    'C/C++',
    'CI/CD',
    'CSS',
    'Cypress',
    'Dart',
    'database design',
    'Flutter',
    'formal verification',
    'GCP',
    'Git',
    'GitHub',
    'Gradle',
    'HTML',
    'iOS',
    'iPhone',
    'JavaScript',
    'JetBrains',
    'Jira',
    'JS',
    'Linux',
    'macOS',
    'Make',
    'Maven',
    'NoSQL',
    'object oriented programming',
    'PHP',
    'Prisma',
    'Python',
    'Racket',
    'relational databases',
    'scripting',
    'Shell',
    'SQL',
    'Swift',
    'Tailwind CSS',
    'Vim',
    'VSCode',
    'Yarn',
  ],
} as const;
