export default {
  name: 'TJ Mazeika',
  position: 'Software Engineer',
  location: 'Austin, TX',
  email: 'mazeika.tj@gmail.com',
  githubUsername: 'tmazeika',
  skills: [
    {
      category: 'Languages',
      items: ['TypeScript', 'Go', 'Java', 'Kotlin', 'C#', 'C/C++'],
    },
    {
      category: 'Tools',
      items: ['Node.js/Next.js', 'Vercel', 'Firebase', 'MongoDB', 'PostgreSQL', 'Docker', '*nix'],
    },
    {
      category: 'Interests',
      items: [
        'Full-stack web development',
        'operating systems',
        'compilers',
        'programming languages',
        'functional programming',
        'optimization',
      ],
    },
  ],
  education: [
    {
      company: 'Northeastern University',
      position: 'Bachelor of Science in Computer Science, summa cum laude',
      location: 'Boston, MA',
      start: 'September 2018',
      end: 'December 2021',
      // body: 'Honors: summa cum laude (GPA: 3.9/4.0)',
    },
  ],
  experience: [
    {
      company: 'Urban Emu',
      position: 'Software Engineer',
      location: 'Remote',
      start: 'January 2022',
      end: 'Present',
      body: [
        "Produced the agency's first fully custom and interactive React SPA, expanding the breadth of development services available to clients.",
        'Coordinated production deployments to secured and US government-owned cloud environments.',
        'Automated time-tracking synchronization between Google Calendar and FreshBooks company-wide to reduce unbillable time spent on manual entry.',
      ],
    },
    {
      company: 'FoldLeft',
      position: 'Founder & Software Engineer',
      location: 'Remote',
      start: 'November 2020',
      end: 'Present',
      body: [
        'Founded an LLC to offer web development services to several small businesses and startups; started greenfield projects and enhanced existing ones.',
        'Bootstrapped a fintech startup from Figma designs; continuously gathered requirements from the client and promptly responded to feedback throughout.',
      ],
    },
    {
      company: 'AIR Worldwide',
      position: 'Software Engineer Co-op',
      location: 'Boston, MA',
      start: 'January',
      end: 'June 2021',
      body: [
        'Enriched product owner insights into developer productivity by tracking Azure DevOps activity from its REST and OData API endpoints; displayed in graphs with the Highcharts library.',
        'Boosted the performance of an internal .NET and React application by 90% through more modern data loading techniques.',
        'Pair-programmed with team members and submitted code reviews to promote code quality.',
      ],
    },
    {
      company: 'Digitas',
      position: 'DevOps Engineer Co-op',
      location: 'Boston, MA',
      start: 'January',
      end: 'July 2020',
      body: [
        'Streamlined front-end QA automation processes with Selenium Java.',
        'Wrote clear and concise documentation for deploying an SAP Hybris and Adobe AEM application to staging and production clusters, improving the success rate and consistency of manual deployments.',
        'Utilized AWS audio transcription and video text recognition services for faster QA of video content.',
      ],
    },
  ],
  keywords: [
    'Agile',
    'Android',
    'backend',
    'Bash',
    'CI/CD',
    'CSS',
    'Cypress',
    'Dart',
    'database design',
    'Flutter',
    'formal verification',
    'GCP',
    'Git',
    'GitHub',
    'Gradle',
    'HTML',
    'iOS',
    'iPhone',
    'JavaScript',
    'JetBrains',
    'Jira',
    'JS',
    'Linux',
    'macOS',
    'Make',
    'Maven',
    'NoSQL',
    'object oriented programming',
    'PHP',
    'Prisma',
    'Python',
    'Racket',
    'relational databases',
    'scripting',
    'Shell',
    'SQL',
    'Swift',
    'Tailwind CSS',
    'Vim',
    'VSCode',
    'Yarn',
  ],
} as const;
